# Generated by Django 5.2.15 on 2026-07-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_profile_otp_code_profile_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
