# Generated by Django 5.2.15 on 2026-07-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_profile_allergies_profile_blood_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_benefits',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='medical_aid_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
