# Generated by Django 5.2.15 on 2026-07-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_profile_change_password_on_next_login_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellMedMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_number', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.CharField(blank=True, max_length=120)),
                ('address', models.TextField(blank=True)),
            ],
        ),
    ]
