# Generated by Django 5.2.15 on 2026-07-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_cellmedmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='timezone',
            field=models.CharField(default='Africa/Johannesburg', max_length=100),
        ),
    ]
