# Generated by Django 5.2.15 on 2026-07-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_appointment_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('booked', 'Booked'), ('verified', 'Verified'), ('start', 'Start'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20),
        ),
    ]
