# Generated by Django 5.2.15 on 2026-07-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthread',
            name='is_doctor_typing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='is_patient_typing',
            field=models.BooleanField(default=False),
        ),
    ]
