# Generated by Django 5.2.15 on 2026-07-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_chatthread_is_doctor_typing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.TextField(blank=True),
        ),
    ]
