# Generated by Django 5.2.15 on 2026-07-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_appointment_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthread',
            name='last_doctor_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='last_patient_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
