# Generated by Django 5.2.15 on 2026-07-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_failedloginattempt_appointment_reminder_1h_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellmedmember',
            name='date_joined',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cellmedmember',
            name='id_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cellmedmember',
            name='insurer',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='cellmedmember',
            name='plan',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_joined',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='insurer',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
