# Generated by Django 5.2.15 on 2026-07-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_cellmedmember_date_joined_cellmedmember_id_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor_qualifications',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor_registration_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor_signature',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='prescription',
            name='drugs_json',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient_age',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='clinic_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='doctor_qualifications',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='doctor_registration_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='signature_data',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='title',
            field=models.CharField(default='Prescription', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='has_benefits',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='medical_aid_status',
            field=models.CharField(default='Active', max_length=50),
        ),
    ]
