# Generated by Django 5.2.14 on 2026-08-04 09:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_prescription_appointment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('booked', 'Booked'), ('verified', 'Verified'), ('start', 'Start'), ('done', 'Done'), ('cancelled', 'Cancelled')], db_index=True, default='upcoming', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time_label',
            field=models.CharField(db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='audittrail',
            name='action',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='audittrail',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='cellmedmember',
            name='email',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='cellmedmember',
            name='membership_number',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='record_type',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(db_index=True, default='unread', max_length=20),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='status',
            field=models.CharField(db_index=True, default='Ready for review', max_length=50),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor', 'date', 'status'], name='api_appoint_doctor__967589_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient', 'date'], name='api_appoint_patient_eb23c7_idx'),
        ),
        migrations.AddIndex(
            model_name='audittrail',
            index=models.Index(fields=['user', 'timestamp'], name='api_audittr_user_id_bce528_idx'),
        ),
        migrations.AddIndex(
            model_name='audittrail',
            index=models.Index(fields=['action', 'timestamp'], name='api_audittr_action_4442e5_idx'),
        ),
        migrations.AddIndex(
            model_name='cellmedmember',
            index=models.Index(fields=['membership_number', 'email'], name='api_cellmed_members_868ba2_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['patient', 'record_type'], name='api_medical_patient_bf8fc8_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['created_at'], name='api_medical_created_e48cc5_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['patient', 'created_at'], name='api_prescri_patient_3237d0_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'cancelled'), _negated=True), fields=('doctor', 'date', 'time_label'), name='unique_active_doctor_appointment_slot'),
        ),
    ]
