from django.urls import path
from rest_framework.authtoken.views import obtain_auth_token

from .views import (
    AvailabilityView,
    ChatThreadView,
    ChatTypingView,
    DashboardView,
    LoginView,
    LogoutView,
    MeView,
    NoteView,
    RegisterView,
    DoctorsView,
    PatientsView,
    AppointmentView,
    PrescriptionView,
    MedicalRecordView,
    NotificationView,
    AdminActionView,
    LookupMemberView,
    VerifyOTPView,
    ResendOTPView,
    DoctorAvailabilityView,
    AdminReportsView,
    SysAdminUsersListView,
    SysAdminCreateUserView,
    SysAdminResetPasswordView,
    SysAdminAuditTrailsView,
    UploadCellMedMembersView,
    ForceChangePasswordView,
    SysAdminUpdateUserView,
    SysAdminDeleteUserView,
    PasswordResetRequestView,
    PasswordResetConfirmView,
    SysAdminAddMemberView,
    SysAdminMembersListView,
    SysAdminUpdateMemberView,
    SysAdminDeleteMemberView,
    SecureRecordDownloadView
)

urlpatterns = [
    path('auth/register/', RegisterView.as_view()),
    path('auth/login/', LoginView.as_view()),
    path('auth/verify-otp/', VerifyOTPView.as_view()),
    path('auth/resend-otp/', ResendOTPView.as_view()),
    path('auth/lookup-member/', LookupMemberView.as_view()),

    path('auth/logout/', LogoutView.as_view()),
    path('auth/me/', MeView.as_view()),
    path('auth/token/', obtain_auth_token),
    path('auth/force-change-password/', ForceChangePasswordView.as_view()),
    path('auth/password-reset-request/', PasswordResetRequestView.as_view()),
    path('auth/password-reset-confirm/', PasswordResetConfirmView.as_view()),

    path('dashboard/', DashboardView.as_view()),
    path('chat/thread/', ChatThreadView.as_view()),
    path('chat/thread/typing/', ChatTypingView.as_view()),
    path('doctor/note/', NoteView.as_view()),
    path('doctor/availability/', AvailabilityView.as_view()),
    path('doctors/', DoctorsView.as_view()),
    path('doctors/<int:doctor_id>/availability/', DoctorAvailabilityView.as_view()),
    path('patients/', PatientsView.as_view()),
    path('appointments/', AppointmentView.as_view()),
    path('prescriptions/', PrescriptionView.as_view()),
    path('records/', MedicalRecordView.as_view()),
    path('records/<int:record_id>/download/', SecureRecordDownloadView.as_view()),
    path('notifications/', NotificationView.as_view()),
    path('admin/action/', AdminActionView.as_view()),
    path('admin/reports/', AdminReportsView.as_view()),
    path('admin/sysadmin/users/', SysAdminUsersListView.as_view()),
    path('admin/sysadmin/create-user/', SysAdminCreateUserView.as_view()),
    path('admin/sysadmin/reset-password/', SysAdminResetPasswordView.as_view()),
    path('admin/sysadmin/update-user/', SysAdminUpdateUserView.as_view()),
    path('admin/sysadmin/delete-user/', SysAdminDeleteUserView.as_view()),
    path('admin/sysadmin/audit-trails/', SysAdminAuditTrailsView.as_view()),
    path('admin/sysadmin/upload-members/', UploadCellMedMembersView.as_view()),
    path('admin/sysadmin/add-member/', SysAdminAddMemberView.as_view()),
    path('admin/sysadmin/members/', SysAdminMembersListView.as_view()),
    path('admin/sysadmin/update-member/', SysAdminUpdateMemberView.as_view()),
    path('admin/sysadmin/delete-member/', SysAdminDeleteMemberView.as_view()),
]


